version: '3'

services:
  db:
    image: postgres
  web:
    build: ./web/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/web/
    ports:
      - "8000:8000"
    depends_on:
      - db